package logic_subsystem;

public enum RequestType {
	// Game logic requests
	LOGIC_CREATE_PLAYER, LOGIC_DELETE_PLAYER, LOGIC_KILL_PLAYER, LOGIC_RESPAWN_PLAYER, LOGIC_SPAWN_PLAYER, LOGIC_MOVE_PLAYER, LOGIC_DAMAGE_PLAYER,
	LOGIC_RENAME_PLAYER,

	// Rendering requests
	RENDERING_RENDER_PLAYER
}
